name: lobe-chat-database
services:
  network-service:
    image: alpine
    container_name: lobe-network
    ports:
      - '${LOGTO_PORT}:${LOGTO_PORT}' # Logto
      - '3002:3002' # Logto Admin
      - '${LOBE_PORT}:3210' # LobeChat
    command: tail -f /dev/null
    networks:
      - lobe-network

  logto:
    image: svhd/logto
    container_name: lobe-logto
    network_mode: 'service:network-service'
    depends_on:
      postgresql:
        condition: service_healthy
    environment:
      - 'TRUST_PROXY_HEADER=1'
      - 'PORT=${LOGTO_PORT}'
      - 'DB_URL=postgresql://postgres:${POSTGRES_PASSWORD}@postgresql:5432/logto'
      - 'ENDPOINT=http://localhost:${LOGTO_PORT}'
      - 'ADMIN_ENDPOINT=http://localhost:3002'
    entrypoint: ['sh', '-c', 'npm run cli db seed -- --swe && npm start']

  lobe:
    build:
      context: ../../../
      dockerfile: Dockerfile.database
    container_name: lobe-chat
    network_mode: 'service:network-service'
    depends_on:
      postgresql:
        condition: service_healthy
      network-service:
        condition: service_started
      minio:
        condition: service_started
      logto:
        condition: service_started

    environment:
      - 'APP_URL=http://localhost:3210'
      - 'NEXT_AUTH_SSO_PROVIDERS=logto'
      - 'KEY_VAULTS_SECRET=Kix2wcUONd4CX51E/ZPAd36BqM4wzJgKjPtz2sGztqQ='
      - 'NEXT_AUTH_SECRET=2a60e2370557f86f6e4b27013a30f380'
      - 'NEXTAUTH_URL=http://localhost:${LOBE_PORT}/api/auth'
      - 'DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@postgresql:5432/${LOBE_DB_NAME}'
      - 'S3_ENDPOINT=http://localhost:${MINIO_PORT}'
      - 'S3_BUCKET=${MINIO_LOBE_BUCKET}'
      - 'S3_PUBLIC_DOMAIN=http://localhost:${MINIO_PORT}'
      - 'S3_ENABLE_PATH_STYLE=1'
      - 'S3_ACCESS_KEY_ID=${MINIO_ROOT_USER}'
      - 'S3_SECRET_ACCESS_KEY=${MINIO_ROOT_PASSWORD}'
      - 'NEXT_PUBLIC_SERVICE_MODE=server'
      - 'NEXT_PUBLIC_ENABLE_AUTH=true'
      - 'NEXT_PUBLIC_REQUIRE_LOGIN=true'
      - 'AUTH_LOGTO_ID=${AUTH_LOGTO_ID}'  # Add this line
      - 'AUTH_LOGTO_SECRET=${AUTH_LOGTO_SECRET}'  # Add this line
      - 'AUTH_LOGTO_ISSUER=http://localhost:${LOGTO_PORT}/oidc'
      - 'UVX_PLUGIN_SERVER=http://word-mcp:3000'
    env_file:
      - .env
    restart: always

volumes:
  data:
    driver: local

networks:
  lobe-network:
    driver: bridge
